site_name: rk

theme:
  name: readthedocs
  color_mode: dark
  features:
    - navigation.tabs
    - navigation.footer
    - content.code.annotate
    - content.code.copy
  palette:
    scheme: slate
  font:
    text: sans-serif
